version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ramadhan_ceria_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin#1234
      POSTGRES_DB: ramadhan_ceria
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ramadhan_ceria_backend
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - JWT_SECRET=rahasia_super_aman_ganti_ini
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Admin#1234
      - DB_NAME=ramadhan_ceria
    depends_on:
      postgres-db:
        condition: service_started
    restart: unless-stopped

  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ramadhan_ceria_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3005
    depends_on:
      - backend-api
    restart: unless-stopped

volumes:
  pgdata:
